# Generated by Django 3.1.3 on 2022-07-23 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('IdUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('fotoUsuario', models.ImageField(default='usuarios/usuario.png', upload_to='usuarios')),
                ('TipoUsuario', models.CharField(blank=True, choices=[('Administrador', 'Administrador'), ('Auxiliar', 'Auxiliar')], default='Auxiliar', max_length=100, null=True)),
                ('FechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('Departamento', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=10)),
                ('usuid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Datos usuario',
                'verbose_name_plural': 'Datos usuarios',
            },
        ),
    ]
