# Generated by Django 3.1.3 on 2022-09-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ferre', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='telefonoRepresentante',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
