# Generated by Django 3.1.3 on 2022-07-23 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ferre', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='fotoUsuario',
            new_name='FotoUsuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='Departamento',
        ),
    ]
