# Generated by Django 3.1.3 on 2022-07-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ferre', '0002_auto_20220723_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('Idcliente', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Direccion', models.CharField(max_length=50)),
                ('Telefono', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Datos cliente',
                'verbose_name_plural': 'Datos clientes',
            },
        ),
    ]
