# Generated by Django 3.1.3 on 2022-07-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ferre', '0003_clientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='CedulaRepresentante',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='NombreRepresentante',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='Tipocliente',
            field=models.CharField(choices=[('Persona natural', 'Persona natural'), ('Personeria juridica', 'Pesoneria juridica')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientes',
            name='Idcliente',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='Nombre',
            field=models.CharField(max_length=100),
        ),
    ]
