# Generated by Django 3.1.3 on 2022-07-24 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ferre', '0004_auto_20220724_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='Nombre',
            new_name='Nombrecompleto',
        ),
    ]
