# Generated by Django 3.1.3 on 2022-08-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ferre', '0007_clientes_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='ClaseProveedor',
            field=models.CharField(choices=[('Fabricantes', 'Persona natural'), ('Minoristas', 'Pesoneria juridica'), ('Mayorista', 'Pesoneria juridica'), ('Distribuidor', 'Pesoneria juridica')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='Correo',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='Rut',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
