# Generated by Django 3.1.3 on 2022-08-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ferre', '0009_auto_20220816_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('IdProducto', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('NombreProducto', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('Proveedor', models.CharField(max_length=50)),
                ('Stock', models.IntegerField(max_length=50, null=True)),
                ('precioUnidad', models.IntegerField(max_length=50, null=True)),
                ('Historico', models.IntegerField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Dato producto',
                'verbose_name_plural': 'Datos productos',
            },
        ),
    ]
