# Generated by Django 3.1.3 on 2022-08-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ferre', '0010_productos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='categoria',
            new_name='Categoria',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='cuentapago1',
            field=models.IntegerField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='cuentapago2',
            field=models.IntegerField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='Rut',
            field=models.IntegerField(max_length=50, null=True),
        ),
    ]
