# Generated by Django 3.1.3 on 2022-08-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ferre', '0011_auto_20220817_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='Rut',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='cuentapago1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='cuentapago2',
            field=models.IntegerField(null=True),
        ),
    ]
