# Generated by Django 3.1.3 on 2022-08-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ferre', '0012_auto_20220817_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='Historico',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='Stock',
            field=models.IntegerField(null=True),
        ),
    ]
