# Generated by Django 3.1.3 on 2022-08-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ferre', '0014_auto_20220817_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='telefonoRepresentante',
            field=models.IntegerField(null=True),
        ),
    ]
