# Generated by Django 3.1.3 on 2022-08-17 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ferre', '0015_clientes_telefonorepresentante'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='TelefonoRepresentante',
            field=models.IntegerField(null=True),
        ),
    ]
