# Generated by Django 3.1.3 on 2022-08-17 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ferre', '0016_proveedor_telefonorepresentante'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='tipocuenta1',
            field=models.CharField(choices=[('Cuenta de ahorro', 'Cuenta de ahorro'), ('Cuenta corriente', 'Cuenta corriente')], max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='tipocuenta2',
            field=models.CharField(choices=[('Cuenta de ahorro', 'Cuenta de ahorro'), ('Cuenta corriente', 'Cuenta corriente')], max_length=35, null=True),
        ),
    ]
