# Generated by Django 3.1.3 on 2022-08-17 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ferre', '0017_auto_20220817_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='TelefonoRepresentante',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='cuentapago1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='cuentapago2',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
