# Generated by Django 3.1.3 on 2022-08-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ferre', '0018_auto_20220817_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='precioUnidad',
            new_name='PrecioCompra',
        ),
        migrations.AddField(
            model_name='productos',
            name='PrecioVenta',
            field=models.IntegerField(null=True),
        ),
    ]
