# Generated by Django 3.1.3 on 2022-08-21 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ferre', '0020_productos_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='Proveedor',
        ),
    ]
