# Generated by Django 3.1.3 on 2022-08-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ferre', '0021_remove_productos_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('IdVentas', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('Fecha', models.DateTimeField(auto_now=True)),
                ('Valor', models.IntegerField(null=True)),
                ('Cantidad', models.IntegerField(null=True)),
                ('Cliente', models.CharField(max_length=100, null=True)),
                ('Vendedor', models.CharField(max_length=100)),
                ('Domicilio', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=5)),
                ('Productos', models.ManyToManyField(to='Ferre.Productos')),
            ],
            options={
                'verbose_name': 'Dato venta',
                'verbose_name_plural': 'Datos ventas',
                'ordering': ['Fecha'],
            },
        ),
    ]
