# Generated by Django 3.1.3 on 2022-08-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ferre', '0022_ventas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='IdVentas',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
