# Generated by Django 3.1.3 on 2022-08-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ferre', '0023_auto_20220821_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='IdProducto',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
