# Generated by Django 3.1.3 on 2022-09-02 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ferre', '0024_auto_20220821_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('IdDomicilio', models.AutoField(primary_key=True, serialize=False)),
                ('Estado', models.CharField(max_length=15)),
                ('Direccion', models.CharField(max_length=60)),
                ('FechaEntrega', models.DateTimeField(auto_now=True)),
                ('IdVenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ferre.ventas')),
            ],
            options={
                'verbose_name': 'Dato venta',
                'verbose_name_plural': 'Datos ventas',
                'ordering': ['FechaEntrega'],
            },
        ),
    ]
