# Generated by Django 3.1.3 on 2022-09-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ferre', '0025_domicilio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domicilio',
            name='Estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Entregado', 'Entregado')], max_length=15),
        ),
    ]
