# Generated by Django 3.1.3 on 2022-09-02 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ferre', '0026_auto_20220902_1202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domicilio',
            options={'ordering': ['FechaEntrega'], 'verbose_name': 'Dato domicilio', 'verbose_name_plural': 'Datos domicilios'},
        ),
        migrations.RemoveField(
            model_name='productos',
            name='PrecioCompra',
        ),
    ]
