# Generated by Django 3.1.3 on 2022-09-03 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ferre', '0027_auto_20220902_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='Direccion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='Telefono',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='Vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ferre.usuario'),
        ),
    ]
