# Generated by Django 3.1.3 on 2022-09-03 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ferre', '0028_auto_20220903_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='Productos',
        ),
    ]
