# Generated by Django 3.1.3 on 2022-09-03 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ferre', '0029_remove_ventas_productos'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroVentas',
            fields=[
                ('IdRegistroVenta', models.AutoField(primary_key=True, serialize=False)),
                ('Cantidad', models.CharField(max_length=100, null=True)),
                ('ValorUni', models.CharField(max_length=100, null=True)),
                ('ValorTotal', models.CharField(max_length=100, null=True)),
                ('IdProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ferre.productos')),
                ('IdVenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ferre.ventas')),
            ],
            options={
                'verbose_name': 'Registro Venta',
                'verbose_name_plural': 'Registro Ventas',
            },
        ),
    ]
