# Generated by Django 3.1.3 on 2022-09-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ferre', '0030_registroventas'),
    ]

    operations = [
        migrations.AddField(
            model_name='domicilio',
            name='Contacto',
            field=models.CharField(default=3136928210, max_length=60),
            preserve_default=False,
        ),
    ]
